spring.application.name=eBook

#  Database config
spring.datasource.url=jdbc:mysql://localhost:3306/ebook_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#  Cache config
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=5m
spring.cache.caffeine.record-stats=true
